export const lightTheme = {
    body: '#FFF',
    headerBody: '#FFF',
    text: '#363537',
    toggleBorder: '#363537',
    background: '#363537',
    headerIconColor: '#363537',
    headerIconBackgroundColor: 'white',
    headerBorderBottom: '2px solid',
    zipCodeInputColor: 'black',
    thermoPic: '/assets/thermometer-fahrenheit-light.svg',
    resultCardButtonBackground: {true: 'black', false: 'white'},
    resultCardButtonColor: {true: 'white', false: 'black'},
    resultCardBorder: '1px solid black',
    notificationTextColor: {positive: '#FAFAFA', warning: '#363537', negative: '#FAFAFA'},
};

export const darkTheme = {
    body: '#363537',
    headerBody: 'black',
    text: '#FAFAFA',
    toggleBorder: '#6B8096',
    background: '#999',
    headerIconColor: 'rgb(34 197 94)',
    headerIconBackgroundColor: 'grey',
    borderBottom: 'revert',
    zipCodeInputColor: 'white',
    thermoPic: '/assets/thermometer-fahrenheit-dark.svg',
    resultCardButtonBackground: {true: 'black', false: 'white'},
    resultCardButtonColor: {true: 'white', false: 'black'},
    resultCardBorder: '1px solid white',
    notificationTextColor: {positive: '#FAFAFA', warning: '#363537', negative: '#FAFAFA'},
};
